"""Setting indexes for provider_npi and net_fee

Revision ID: 4f17ddf2c015
Revises: d97764481c5f
Create Date: 2025-01-15 02:14:58.075176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f17ddf2c015'
down_revision: Union[str, None] = 'd97764481c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_claim_net_fee'), 'claim', ['net_fee'], unique=False)
    op.create_index(op.f('ix_claim_provider_npi'), 'claim', ['provider_npi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_provider_npi'), table_name='claim')
    op.drop_index(op.f('ix_claim_net_fee'), table_name='claim')
    # ### end Alembic commands ###
